Repository RaspberryWallet/Backend, pull requests merged in 2018-10, with the labels that each got.

#27 Added a simple test of temperature monitor for the system.
  Manager/src/main/java/io/raspberrywallet/manager/ExampleMockManager.java
  Manager/src/main/java/io/raspberrywallet/manager/Main.java
  Manager/src/main/java/io/raspberrywallet/manager/Manager.java
  Manager/src/main/java/io/raspberrywallet/manager/linux/Executable.java
  Manager/src/main/java/io/raspberrywallet/manager/linux/TemperatureMonitor.java
Labels: enhancement

#28 Utilities continuation
  Manager/src/main/java/io/raspberrywallet/manager/Manager.java
  Manager/src/main/java/io/raspberrywallet/manager/linux/Executable.java
  Manager/src/main/java/io/raspberrywallet/manager/linux/TemperatureMonitor.java
  Manager/src/test/java/io/raspberrywallet/manager/ManagerTest.java
  ServerHttp/src/main/java/io/raspberrywallet/Manager.java
  ServerHttp/src/main/kotlin/io/raspberrywallet/ktor/Server.kt
  ServerHttp/src/main/kotlin/io/raspberrywallet/mock/ManagerMock.kt
  ServerHttp/src/main/kotlin/io/raspberrywallet/server/Server.kt
Labels: enhancement

#32 PIN Module
  Manager/src/main/java/io/raspberrywallet/manager/ExampleMockManager.java
  Manager/src/main/java/io/raspberrywallet/manager/Main.java
  Manager/src/main/java/io/raspberrywallet/manager/Manager.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/ExampleModule.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/Module.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/PinModule.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/PushButtonModule.java
  ServerHttp/pom.xml
  ServerHttp/src/main/java/io/raspberrywallet/Manager.java
  ServerHttp/src/main/java/io/raspberrywallet/module/Module.java
  ServerHttp/src/main/kotlin/io/raspberrywallet/Main.kt
  ServerHttp/src/main/kotlin/io/raspberrywallet/ktor/KtorServer.kt
  ServerHttp/src/main/kotlin/io/raspberrywallet/ktor/Server.kt
  ServerHttp/src/main/kotlin/io/raspberrywallet/mock/ManagerMock.kt
  ServerHttp/src/main/resources/assets/asset-manifest.json
  ServerHttp/src/main/resources/assets/index.html
  ServerHttp/src/main/resources/assets/service-worker.js
  ServerHttp/src/main/resources/assets/static/js/main.17cf674d.js
  ServerHttp/src/main/resources/assets/static/js/main.8824f53c.js
  ServerHttp/src/main/resources/logback.xml
  pom.xml
Labels: enhancement

#36 Limit http sever for RPI Zero constrains
  Manager/src/main/java/io/raspberrywallet/manager/Main.java
  ServerHttp/pom.xml
  ServerHttp/src/main/kotlin/io/raspberrywallet/Main.kt
  ServerHttp/src/main/kotlin/io/raspberrywallet/ktor/KtorServer.kt
  ServerHttp/src/main/kotlin/io/raspberrywallet/mock/ManagerMock.kt
  ServerHttp/src/main/kotlin/io/raspberrywallet/server/Server.kt
Labels: bugfix, enhancement, refactor

#56 Standardize modules packaging and naming rule
  Manager/build.gradle
  Manager/compileModules.sh
  Manager/src/main/java/io/raspberrywallet/manager/Main.java
  Manager/src/main/java/io/raspberrywallet/manager/Manager.java
  Manager/src/main/java/io/raspberrywallet/manager/bitcoin/Bitcoin.java
  Manager/src/main/java/io/raspberrywallet/manager/cli/Opts.java
  Manager/src/main/java/io/raspberrywallet/manager/cryptography/sharedsecret/blakley/Blakley.java
  Manager/src/main/java/io/raspberrywallet/manager/cryptography/sharedsecret/shamir/Shamir.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/Module.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/ModuleClassLoader.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/example/ExampleModule.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/pin/PinModule.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/pushbutton/PushButtonModule.java
  Manager/src/test/java/io/raspberrywallet/manager/ManagerTest.java
  Manager/src/test/java/io/raspberrywallet/manager/bitcoin/BitcoinTest.java
  Manager/src/test/java/io/raspberrywallet/manager/database/DatabaseTest.java
  README.md
  Scripts/modules/compileJarSignAndCopyModules.py
  ServerHttp/src/main/java/io/raspberrywallet/WalletNotInitialized.java
  ServerHttp/src/main/java/io/raspberrywallet/contract/Manager.java
  ServerHttp/src/main/java/io/raspberrywallet/contract/RequiredInputNotFound.java
  ServerHttp/src/main/java/io/raspberrywallet/contract/Response.java
  ServerHttp/src/main/java/io/raspberrywallet/contract/WalletNotInitialized.java
  ServerHttp/src/main/java/io/raspberrywallet/contract/WalletStatus.java
  ServerHttp/src/main/java/io/raspberrywallet/contract/module/Module.java
  ServerHttp/src/main/java/io/raspberrywallet/contract/module/ModuleState.java
  ServerHttp/src/main/java/io/raspberrywallet/contract/step/InputStep.java
  ServerHttp/src/main/java/io/raspberrywallet/contract/step/SimpleStep.java
  ServerHttp/src/main/java/io/raspberrywallet/contract/step/Step.java
  ServerHttp/src/main/kotlin/io/raspberrywallet/ktor/KtorServer.kt
  ServerHttp/src/main/kotlin/io/raspberrywallet/mock/ManagerMock.kt
  ServerHttp/src/main/kotlin/io/raspberrywallet/server/Server.kt
  modules/ExampleModule.jar
  modules/PinModule.jar
Labels: enhancement

#51 Module authorizationserver
  Manager/pom.xml
  Manager/src/main/java/io/raspberrywallet/manager/Manager.java
  Manager/src/main/java/io/raspberrywallet/manager/common/http/ApacheHttpClient.java
  Manager/src/main/java/io/raspberrywallet/manager/common/http/SecureApacheApacheHttpClient.java
  Manager/src/main/java/io/raspberrywallet/manager/common/http/UnsecureApacheApacheHttpClient.java
  Manager/src/main/java/io/raspberrywallet/manager/common/interfaces/Destroyable.java
  Manager/src/main/java/io/raspberrywallet/manager/common/readers/Reader.java
  Manager/src/main/java/io/raspberrywallet/manager/common/readers/WalletUUIDReader.java
  Manager/src/main/java/io/raspberrywallet/manager/common/wrappers/Base64Secret.java
  Manager/src/main/java/io/raspberrywallet/manager/common/wrappers/ByteWrapper.java
  Manager/src/main/java/io/raspberrywallet/manager/common/wrappers/Credentials.java
  Manager/src/main/java/io/raspberrywallet/manager/common/wrappers/Secret.java
  Manager/src/main/java/io/raspberrywallet/manager/common/wrappers/Token.java
  Manager/src/main/java/io/raspberrywallet/manager/cryptography/common/Password.java
  Manager/src/main/java/io/raspberrywallet/manager/cryptography/crypto/CryptoObject.java
  Manager/src/main/java/io/raspberrywallet/manager/cryptography/crypto/EncryptedObject.java
  Manager/src/main/java/io/raspberrywallet/manager/cryptography/crypto/algorithms/AESParams.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/Module.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/authorizationserver/APIKeys.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/authorizationserver/AuthorizationServerAPI.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/authorizationserver/AuthorizationServerConf.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/authorizationserver/AuthorizationServerModule.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/authorizationserver/RequestException.java
  Manager/src/main/java/io/raspberrywallet/manager/session/SessionToken.java
  Manager/src/test/java/io/raspberrywallet/manager/cryptography/crypto/AESObjectsTests.java
  Manager/src/test/java/io/raspberrywallet/manager/cryptography/crypto/RSAObjectsTests.java
  Manager/src/test/java/io/raspberrywallet/manager/modules/authorizationserver/AuthServerTests.java
Labels: enhancement

#58 remove vertx
  Manager/src/main/java/io/raspberrywallet/manager/Main.java
  Manager/src/main/java/io/raspberrywallet/manager/cli/CliUtils.java
  Manager/src/main/java/io/raspberrywallet/manager/cli/Opts.java
  Manager/src/test/java/io/raspberrywallet/manager/bitcoin/BitcoinJTest.java
  Manager/src/test/java/io/raspberrywallet/manager/bitcoin/PeerMonitor.java
  README.md
  ServerHttp/build.gradle
  ServerHttp/pom.xml
  ServerHttp/src/main/kotlin/io/raspberrywallet/Main.kt
  ServerHttp/src/main/kotlin/io/raspberrywallet/server/KtorServer.kt
  ServerHttp/src/main/kotlin/io/raspberrywallet/server/Main.kt
  ServerHttp/src/main/kotlin/io/raspberrywallet/server/Server.kt
  ServerHttp/src/test/kotlin/io/raspberrywallet/server/MainVerticleTest.kt
Labels: refactor
