Repository RaspberryWallet/Backend, pull requests merged in 2018-11, with the labels that each got.

#78 Websocket
  Manager/src/main/java/io/raspberrywallet/manager/Main.java
  Manager/src/main/java/io/raspberrywallet/manager/Manager.java
  Manager/src/main/java/io/raspberrywallet/manager/bitcoin/Bitcoin.java
  ServerHttp/pom.xml
  ServerHttp/src/main/java/io/raspberrywallet/contract/Manager.java
  ServerHttp/src/main/kotlin/io/raspberrywallet/mock/ManagerMock.kt
  ServerHttp/src/main/kotlin/io/raspberrywallet/server/HtmlPages.kt
  ServerHttp/src/main/kotlin/io/raspberrywallet/server/KtorServer.kt
  ServerHttp/src/main/kotlin/io/raspberrywallet/server/Paths.kt
Labels: enhancement

#84 AuthorizationServer module HTTPS support
  Manager/src/main/java/io/raspberrywallet/manager/common/generators/RandomStringGenerator.java
  Manager/src/main/java/io/raspberrywallet/manager/common/http/ApacheHttpClient.java
  Manager/src/main/java/io/raspberrywallet/manager/common/http/SecureApacheHttpClient.java
  Manager/src/main/java/io/raspberrywallet/manager/common/http/UnsecureApacheHttpClient.java
  Manager/src/main/java/io/raspberrywallet/manager/common/wrappers/Base64Secret.java
  Manager/src/main/java/io/raspberrywallet/manager/common/wrappers/Credentials.java
  Manager/src/main/java/io/raspberrywallet/manager/common/wrappers/Secret.java
  Manager/src/main/java/io/raspberrywallet/manager/cryptography/common/Password.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/authorizationserver/AuthorizationServerAPI.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/authorizationserver/AuthorizationServerConfig.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/authorizationserver/AuthorizationServerModule.java
  Manager/src/test/java/io/raspberrywallet/manager/ConfigurationTest.java
  Manager/src/test/java/io/raspberrywallet/manager/commons/CustomConfig.java
  Manager/src/test/java/io/raspberrywallet/manager/cryptography/crypto/AESObjectsTests.java
  Manager/src/test/java/io/raspberrywallet/manager/modules/authorizationserver/AuthServerSecuredTests.java
  Manager/src/test/java/io/raspberrywallet/manager/modules/authorizationserver/AuthServerTests.java
  Manager/src/test/java/io/raspberrywallet/manager/modules/authorizationserver/AuthServerUnsecuredTests.java
  config.yaml
Labels: bugfix, don't merge yet, enhancement

#88 Module Class Refactor
  Manager/src/main/java/io/raspberrywallet/manager/Configuration.java
  Manager/src/main/java/io/raspberrywallet/manager/Main.java
  Manager/src/main/java/io/raspberrywallet/manager/Manager.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/Module.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/authorizationserver/AuthorizationServerModule.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/example/ExampleModule.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/pin/PinModule.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/pushbutton/PushButtonModule.java
  Manager/src/test/java/io/raspberrywallet/manager/ConfigurationTest.java
  Manager/src/test/java/io/raspberrywallet/manager/ManagerTest.java
  Manager/src/test/java/io/raspberrywallet/manager/bitcoin/BitcoinTest.java
  Manager/src/test/java/io/raspberrywallet/manager/modules/authorizationserver/AuthServerSecuredTests.java
  Manager/src/test/java/io/raspberrywallet/manager/modules/authorizationserver/AuthServerUnsecuredTests.java
  Manager/src/test/java/io/raspberrywallet/manager/modules/pin/PinModuleTests.java
  ServerHttp/src/main/java/io/raspberrywallet/contract/InternalModuleException.java
  ServerHttp/src/main/java/io/raspberrywallet/contract/ModuleInitializationException.java
  ServerHttp/src/main/java/io/raspberrywallet/contract/RequiredInputNotFound.java
  ServerHttp/src/main/java/io/raspberrywallet/contract/ServerConfig.java
  ServerHttp/src/main/kotlin/io/raspberrywallet/server/KtorServer.kt
  config.yaml
Labels: bugfix, refactor

#102 Error handling and AuthServer stateless refactor
  Manager/src/main/java/io/raspberrywallet/manager/AutoLockTimer.java
  Manager/src/main/java/io/raspberrywallet/manager/Main.java
  Manager/src/main/java/io/raspberrywallet/manager/Manager.java
  Manager/src/main/java/io/raspberrywallet/manager/bitcoin/Bitcoin.java
  Manager/src/main/java/io/raspberrywallet/manager/bitcoin/WalletCrypter.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/Module.java
  Manager/src/main/java/io/raspberrywallet/manager/modules/authorizationserver/AuthorizationServerModule.java
  Manager/src/test/java/io/raspberrywallet/manager/ManagerTest.java
  Manager/src/test/java/io/raspberrywallet/manager/bitcoin/BitcoinTest.java
  ServerHttp/src/main/java/io/raspberrywallet/contract/IncorrectPasswordException.java
  ServerHttp/src/main/java/io/raspberrywallet/contract/InternalModuleException.java
  ServerHttp/src/main/java/io/raspberrywallet/contract/Manager.java
  ServerHttp/src/main/java/io/raspberrywallet/contract/ModuleInitializationException.java
  ServerHttp/src/main/java/io/raspberrywallet/contract/ModuleUploadException.java
  ServerHttp/src/main/java/io/raspberrywallet/contract/RequiredInputNotFound.java
  ServerHttp/src/main/kotlin/io/raspberrywallet/mock/ManagerMock.kt
  ServerHttp/src/main/kotlin/io/raspberrywallet/server/KtorServer.kt
  ServerHttp/src/main/resources/assets/asset-manifest.json
  ServerHttp/src/main/resources/assets/index.html
  ServerHttp/src/main/resources/assets/service-worker.js
  ServerHttp/src/main/resources/assets/static/js/main.ba69d861.js
  ServerHttp/src/main/resources/assets/static/js/main.f6abf7ea.js
  config.yaml
  raspberry.jks
  raspberry.pfx
Labels: bugfix, enhancement, refactor

#106 Autolock
  Manager/src/main/java/io/raspberrywallet/manager/AutoLockTimer.java
  Manager/src/main/java/io/raspberrywallet/manager/Manager.java
  README.md
  ServerHttp/src/main/resources/assets/asset-manifest.json
  ServerHttp/src/main/resources/assets/index.html
  ServerHttp/src/main/resources/assets/service-worker.js
  ServerHttp/src/main/resources/assets/static/js/main.6bd6976d.js
  ServerHttp/src/main/resources/assets/static/js/main.ba69d861.js
  config.yaml
Labels: enhancement
